<a href="https://colab.research.google.com/github/m22oi/python_workspace/blob/main/06_Numpy_Pandas%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 넘파이(Numpy)

### 넘파이 import
- 외부 패키지이므로 설치하여 사용하여야 하지만 colab에는 기본적으로 설치가 되어있기 때문에 설치할 필요 없이 사용 가능하다.
- numpy는 관용적으로 np라는 별칭을 사용한다.



In [ ]:
import numpy as np

### 직접 원소를 입력해서 다차원 배열 생성하기
- np.array(리스트)

##### 정수형
- 정수형의 default data type은 'int64'이다.
- 운영체제에 따라 달라질 수 있다.

In [ ]:
int_arr = np.array([1,2,3,4])
int_arr #가지고 있는 리스트를 보여짐
print(int_arr) #리스트와 다르게 ,가 없음

[1 2 3 4]


In [ ]:
type(int_arr)

numpy.ndarray

In [ ]:
int_arr.dtype #int32 또는 int64 의미 정수 타입


dtype('int64')

In [ ]:
num_lst =[1,2,3,4]
int_arr2 = np.array(num_lst)
print(int_arr2)

[1 2 3 4]


##### 실수형

In [ ]:
float_arr = np.array([1.1,2.2,3.3,4.4])
print(float_arr)


[1.1 2.2 3.3 4.4]


In [ ]:
float_arr.dtype #실수 타입

dtype('float64')

In [ ]:
np.array([1,2,3,4], dtype=np.float64) #실수형으로 지정

array([1., 2., 3., 4.])

In [ ]:
float_arr

array([1.1, 2.2, 3.3, 4.4])

In [ ]:
#실수형 정수형으로 변환
float_arr.astype(np.int64)
fl_to_int = float_arr.astype(np.int64)
print(fl_to_int)

[1 2 3 4]


In [ ]:
float_arr

array([1.1, 2.2, 3.3, 4.4])

##### 여러 데이터형이 섞여서 들어가더라도 한 가지 데이터형으로 통일된다.

In [ ]:
lst_data = ['1','2','3']
arr = np.array(lst_data)
print(arr)



['1' '2' '3']


In [ ]:
arr.dtype #문자열


dtype('<U1')

In [ ]:
# 여러 데이터형이 섞여 있을 때 사용하는 바이트 사이즈가 큰 형식으로 통일이 이루어진다. int < float < text arry로 들어갈때 하나로 되어야 해서
lst_data = [1,'2',3] #문자로 통일
arr = np.array(lst_data)
print(arr)

['1' '2' '3']


In [ ]:
lst_data = [1,2.,3] # 실수로  통일
arr = np.array(lst_data) #arry 안에는 list로 만들어주면 되는 형태
print(arr)

[1. 2. 3.]


### 범위를 지정하여 다차원 배열 생성
- np.arange(start, stop, step) : 범위를 지정해서 만드는 형태 range 함수로 만드는 형태로 유사함

In [ ]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.arange(0,10,2) #range 함수와 비슷하게 이루어진다.
print(arr)

[0 2 4 6 8]


In [ ]:
arr1 = np.arange(5)
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


### 2차원 배열

In [ ]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr) #행과 열로 해서 매트릭스 형태로 보여짐. 1,2 차원은 자주 만듦

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


### 3차원 배열

In [ ]:
arr3 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]]])
# 리스트 안에 리스트를 만들어서 원소 두개,원소 안에는 네개짜리 두개를 넣는 형태
print(arr) #3차원 어레이를 확인할 수 있다. 대 괄호가 몇개인지를 확인해서 할 수 있다.2행 4열 짜리 3개 있는 정육면체 형태로 만들어지는 형태

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


### 배열의 차원과 크기 알아보기
- 차원 : 배열명.ndim
- 크기 : 배열명.shape

In [ ]:
print(arr1.ndim) #1차원
print(arr2.ndim) #2차원
print(arr3.ndim) #3차원

1
2
3


In [ ]:
print(arr1.shape) #5열 tuple
print(arr2.shape) #3행 4열 tuple 2차원 확인 쉬움
print(arr3.shape) #2행 4열 3개 있음 tuple

(5,)
(3, 4)
(3, 2, 4)


### 배열의 차원 변경
- 배열명.reshape(크기)
- 배열의 차원 변경하는 경우를 많이 쓴다.
reshape을 많이 쓰는데 크기 활용

In [ ]:
arr = np.arange(1,11)
print(arr)
print(arr.ndim) #
print(arr.shape) #1차원

[ 1  2  3  4  5  6  7  8  9 10]
1
(10,)


In [ ]:
arr.reshape(2,5) #2차원
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr.reshape(5,2) #2차원
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [ ]:
arr3 = arr.reshape(5,2) #3차원
print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2
(5, 2)


In [ ]:
arr4 = arr.reshape(3,3) #안됨
print(arr4)
print(arr4.ndim)
print(arr4.shape)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [ ]:
arr4 = arr.reshape(-1,1) #행은 알아서 해줘
print(arr4)
print(arr4.ndim)
print(arr4.shape)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
2
(10, 1)


In [ ]:
arr5 = arr.reshape(1,-1) #열은 알아서 해줘
print(arr5)
print(arr5.ndim)
print(arr5.shape)

[[ 1  2  3  4  5  6  7  8  9 10]]
2
(1, 10)


### 연산
- shape이 같은 넘파이 배열간의 연산 가능

In [ ]:
#shape이 같으면 같은 요소끼리 연산이 되는 형태라고 볼 수 있다.
a = np.array([1,2,3])
b = np.array([3,4,5])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[4 6 8]
[-2 -2 -2]
[ 3  8 15]
[0.33333333 0.5        0.6       ]


In [ ]:
a = np.array([1,2,3])
b = np.array([3,4,5])
print(a==b)
print(a>b)
print(b>a)

[False False False]
[False False False]
[ True  True  True]


In [ ]:
a = np.array([1,2,3])
b = np.array([3,4,5])
c = np.maximum(a,b)
print(c)

[3 4 5]


-   백터화 연산 : 모든 요소에 일괄적으로 연산이 적용된다.

In [ ]:
a = np.array([1,2,3]) #빠르게 계산
print(a+100)
print(a - 1)
print(a * 10000)

[101 102 103]
[0 1 2]
[10000 20000 30000]


###  범위를 지정하고 개수만큼 요소를 갖는 넘파이 배열 생성

In [ ]:
arr = np.linspace(1,10,50) #linspace 함수
print(arr)


[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


### 특별한 형태의 배열 생성
- np.zeros()
- np.ones()
- np.eye()

In [ ]:
arr = np.zeros(10, dtype=int)
print(arr)


[0 0 0 0 0 0 0 0 0 0]


In [ ]:
arr = np.zeros((3,4))
print(arr)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
arr = np.ones(10, dtype=int)
print(arr)
arr = np.ones((2,6))
print(arr)

[1 1 1 1 1 1 1 1 1 1]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
arr = np.eye(5) #딥러닝할 때 쓰임이 있음
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#2행 3열 오류는 안나지만 할 수 있는 만큼만 넣어줌
arr = np.eye(2,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]]


## 판다스(Pandas)

### 판다스 import
- 외부 패키지이므로 설치하여 사용하여야 하지만 colab에는 기본적으로 설치가 되어있기 때문에 설치할 필요 없이 사용 가능하다.
- pandas는 관용적으로 pd라는 별칭을 사용한다.

In [ ]:
import pandas as pd

### 시리즈

#### 시리즈 생성

In [ ]:
s = pd.Series([3,-5,7,4])
s

0    3
1   -5
2    7
3    4
dtype: int64


dtype('int64')

In [ ]:
print(s) #인덱스와 값 데이터 확인 가능
s.dtype #데이터 타입 확인

#### 시리즈 속성
- index
- value

In [ ]:
s.index #인덱스 확인
print(s.index)
s.index.dtype #인덱스의 데이터 타입 확인

Index(['a', 'b', 'c', 'd'], dtype='object')


dtype('O')

In [ ]:
s.values #값 확인
print(s.values)
s.values.dtype #값의 데이터 타입 확인

[ 3 -5  7  4]


dtype('int64')

#### 시리즈 인덱싱

In [ ]:
s = pd.Series([3,-5,7,4], index=['a','b','c','d']) #인덱스 명으로 바꿔서 할 수 있다.
s

a    3
b   -5
c    7
d    4
dtype: int64

In [ ]:
s['a']

3

#### 요소간 연산

In [ ]:
s2 = s*2
s2

a     6
b   -10
c    14
d     8
dtype: int64

#### 시리즈를 데이터프레임으로 변환하기
- to_frame()

In [ ]:
s_to_df = s.to_frame()
s_to_df

0
a  3
b -5
c  7
d  4

In [ ]:
type(s_to_df)

pandas.core.frame.DataFrame

In [ ]:
type(s)

pandas.core.series.Series

### 데이터프레임(DataFrame)
- 데이터 프레임은 중첩된 리스트나 딕셔너리를 통해 생성할 수 있다.

In [ ]:
df = pd.DataFrame([['부산광역시', '051', 3364358],['전라남도','061', 1840921],['강원도', '033', 1535530]]) # 행중심으로 2중 리스트
df


데이터 프레임의 속성
- index, values
- columns,dtype

In [ ]:
#index, values, colums, dtypes
df.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
df.dtypes
#object = pandas string이 없어서 기타 등등 표현 '문자열'에 해당
#문자열로 2번 인덱스도 ''로 넣어기에 표기됨

0    object
1    object
2     int64
dtype: object

In [ ]:
#할당할 수 있고 컬럼도 가능하다.
df.colums =['Division','Code','Population'] #컬럼명 변경
df

<ipython-input-131-b6d8e9d7a04e>:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.colums =['Division','Code','Population'] #컬럼명 변경


Division Code  Population
0    부산광역시  051     3364358
1     전라남도  061     1840921
2      강원도  033     1535530

In [ ]:
df.index = ['a','b','c'] #인덱스 번호, 인덱스 명 구분
df.index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
df

Division Code  Population
a    부산광역시  051     3364358
b     전라남도  061     1840921
c      강원도  033     1535530

In [ ]:
df = pd.DataFrame([['부산광역시', '051', 3364358],['전라남도','061', 1840921],['강원도', '033', 1535530]]) # 행중심으로 2중 리스트
df


df = pd.DataFrame({'Division':['부산광역시', '전라남도', '강원도'],
                  'Code':['051', '061','033'],
                  'Population':[3364358, 1840921, 1535530]}) #딕셔너리로 만들어서 컬럼을 설정해서 열로 만들어진다. 딕셔너리로 만들면 키가 컬럼의 이름으로 들어간다.
df

Division Code  Population
0    부산광역시  051     3364358
1     전라남도  061     1840921
2      강원도  033     1535530

In [ ]:
df.dtypes

Division      object
Code          object
Population     int64
dtype: object

#### 데이터 파일 읽어오기

In [ ]:
df = pd.read_csv('/content/hero.csv')
pd.options.display.float_format ='{:.0f}'.format #소수점 / ctrl enter
#널값이 있으면 안됨
df # datashape을 보고 불러오는 형태가 되어야 한다.

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

#### 데이터 확인하기

In [ ]:
df.shape #행과 열의 개수
df.shape[0] #행의 개수
df.shape[1] #열의 개수

6

In [ ]:
df.head() #앞에서 5개

이름  나이     직업     국적    키            재산
0   아이언맨  58    CEO     미국  174  1.150000e+13
1     토르  45      신  아스가르드  190           NaN
2  스파이더맨  18   고등학생     미국  177  6.000000e+02
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270  1.000000e+09

In [ ]:
df.tail() #뒤에서 5개

이름  나이     직업     국적    키            재산
2  스파이더맨  18   고등학생     미국  177  6.000000e+02
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270  1.000000e+09
5   캡틴마블  25    파일럿     미국  170  3.400000e+08
6  블랙위도우  32    스파이    러시아  170  5.000000e+07

In [ ]:
#전체 데이터 몇개인지 - 행단위로 알려줌
print(len(df))
print(len(df.index))
print(len(df.columns))

7
7
6


In [ ]:
df.values

array([['아이언맨', 58, 'CEO', '미국', 174, 11500000000000.0],
       ['토르', 45, '신', '아스가르드', 190, nan],
       ['스파이더맨', 18, '고등학생', '미국', 177, 600.0],
       ['원더우먼', 27, '공주', '데미스키라', 178, nan],
       ['헐크', 33, '핵물리학자', '미국', 270, 1000000000.0],
       ['캡틴마블', 25, '파일럿', '미국', 170, 340000000.0],
       ['블랙위도우', 32, '스파이', '러시아', 170, 50000000.0]], dtype=object)

In [ ]:
df.info() #종합정보로 info를 확인할 수 있다.
#컬럼, 결측치 null, 타입 확인할 수 있다.
#데이터 크기에 따라서 볼 수 있다. 메모리를 줄여주는 방향으로 데이터를 짜서 실행하기 쉽도록 해야 한다.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 464.0+ bytes


In [ ]:
df.describe() #기술 통계 값
#수치형으로 이루어진 컬럼만 기술통계를 준다.
#count 실제 데이터, mean 평균, std 표준편차, 최소값, 분위수, 최대값

나이           키            재산
count   7.000000    7.000000  5.000000e+00
mean   34.000000  189.857143  2.300278e+12
std    13.466007   35.983462  5.142801e+12
min    18.000000  170.000000  6.000000e+02
25%    26.000000  172.000000  5.000000e+07
50%    32.000000  177.000000  3.400000e+08
75%    39.000000  184.000000  1.000000e+09
max    58.000000  270.000000  1.150000e+13

In [ ]:
1,1,1,2,7,9,10,24,1000 #하나의 값이 튀면 평균이 튀어버리는 상황
평균 : 166.1
중앙값 : 7 #모든 데이터를 중간에 위치한 값. 두개의 평균값이 중앙 값을 쓰기도 한다.
최빈값 : 1
분산 : #각 데이터들이 평균으로 부터 거리를 제공으로 해서 이루어진다.
표준편차 : #분산의 제곱근

5numbers = 최소값, 최대값, 분위수(25%,50%,75%), 평균, 중앙값
평균과 중앙값의 차이가 많이 나는지 확인한다. 이상치를 확인하고 특이한 점을 본다.
전반적 데이터셋을 확인하는 형태로 볼 수 있다.

In [ ]:
#다양한 방법으로 확인하라
df['재산'].mean()

5

In [ ]:
print(df['재산'].median())
print(df['재산'].std())
print(df['재산'].min())
print(df['재산'].max())A
print(df['재산'].quantile(0.25)) #분위수
print(df['재산'].quantile(0.5))
print(df['재산'].quantile(0.75))
print(df['재산'].quantile(1))
print(df['재산'].count())

340000000.0
5142800956894.008
600.0
11500000000000.0
50000000.0
340000000.0
1000000000.0
11500000000000.0
5


In [ ]:
df['재산'].median()

340000000.0

In [ ]:
df['재산'].std()

5142800956894.008

In [ ]:
df['재산'].min()

600.0

In [ ]:
df['재산'].max()

11500000000000.0

In [ ]:
df['재산'].quantile(0.25) #분위수

50000000.0

In [ ]:
df['재산'].quantile(0.5)

340000000.0

In [ ]:
df['재산'].quantile(0.75)

1000000000.0

In [ ]:
df['재산'].quantile(1)

11500000000000.0

In [ ]:
df['재산'].count()

5

In [ ]:
print(df['국적']) #시리즈로 표현
print(df['국적'].unique()) #중복값 제외
print(df['국적'].nunique()) #중복값 제외하고 개수
print(df['국적'].value_counts()) #중복값 제외하고 개수
print(df['키'].nlargest(1)) #제일 큰애,
print(df['키'].nlargest(2)) #상위 두명
print(df.nlargest(1,'키')) #행의 전체 정보를 알려줌
print(df['키'].nsmallest(1)) #제일 작은
print(df.sample()) #랜덤으로 한개
print(df.sample(2)) #랜덤으로 두개

0       미국
1    아스가르드
2       미국
3    데미스키라
4       미국
5       미국
6      러시아
Name: 국적, dtype: object
['미국' '아스가르드' '데미스키라' '러시아']
4
국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64
4    270
Name: 키, dtype: int64
4    270
1    190
Name: 키, dtype: int64
   이름  나이     직업  국적    키         재산
4  헐크  33  핵물리학자  미국  270 1000000000
5    170
Name: 키, dtype: int64
   이름  나이     직업  국적    키         재산
4  헐크  33  핵물리학자  미국  270 1000000000
     이름  나이  직업     국적    키  재산
1    토르  45   신  아스가르드  190 NaN
3  원더우먼  27  공주  데미스키라  178 NaN


In [ ]:
df['국적'] #시리즈로 표현

0       미국
1    아스가르드
2       미국
3    데미스키라
4       미국
5       미국
6      러시아
Name: 국적, dtype: object

In [ ]:
df['국적'].unique() #중복값 제외

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [ ]:
df['국적'].nunique() #중복값 제외하고 개수

4

In [ ]:
df['국적'].value_counts() #중복값 제외하고 개수

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [ ]:
df['키'].nlargest(1) #제일 큰애,

4    270
Name: 키, dtype: int64

In [ ]:
df['키'].nlargest(2) #상위 두명

4    270
1    190
Name: 키, dtype: int64

In [ ]:
df.nlargest(1,'키') #행의 전체 정보를 알려줌

이름  나이     직업  국적    키         재산
4  헐크  33  핵물리학자  미국  270 1000000000

In [ ]:
df['키'].nsmallest(1) #제일 작은

5    170
Name: 키, dtype: int64

In [ ]:
df.sample() #랜덤으로 한개

이름  나이 직업     국적    키  재산
1  토르  45  신  아스가르드  190 NaN

In [ ]:
df.sample(2) #랜덤으로 두개

이름  나이   직업     국적    키             재산
1    토르  45    신  아스가르드  190            NaN
0  아이언맨  58  CEO     미국  174 11500000000000